### PR TITLE
Feature/insert chellenger names

### PR DESCRIPTION
**Pull request by dreardon1021**

### CODE REVIEW

**Comment by CLPena** [comment]
I merged it! Don't forget to git checkout master and git pull origin master to make sure your local master is up to date. Let's hope the JS functions work when all put together!

**Comment by CLPena** [comment]
Just checked and it looks like our buttons are broken. I'll work on it today and see if I can get it working again. If I can, you cool if I just push the bug fix to the master branch?

**Comment by CLPena** [comment]
I commented out your new function to see if the buttons still work and they do. This is good news because it means that the HTML and CSS are probably still fine and the bug is just a conflict between our functions.

**Comment by dreardon1021** [comment]
Awesome! So there is probably a co flicking variable or event listener somewhere. since my function contains local variables I’m guessing it’s probably the event listeners conflicting each other somehow.

I’m doing chores and getting a haircut and then I’m gonna work for 6-8 hours

**Pull request merged**
